 [build]
  command = "apt-get update && apt-get install -y build-essential ruby-dev && bundle install && bundle exec jekyll build"
  publish = "_site"


[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.3.4"
